### ISSUE TITLE
Create a docker-compose 

### ISSUE THREAD

**Issue by MaxLeiter** [MaxLeiter/Drift#6]
Server and client both have their respective Dockerfiles, which seem to work, but they can't communicate with one another.

**Comment by katacarbix** [comment]
I made a rudimentary compose file...

```yaml
version: '3.8'

services:
  server:
    build: ./server
    restart: unless-stopped
    user: 1000:1000
    environment:
      - "PORT=3000"
      - "JWT_SECRET=change_me!"

  client:
    build: ./client
    restart: unless-stopped
    user: 1000:1000
    depends_on:
      - server
    environment:
      - "API_URL=http://server:3000"
    ports:
      - "3748:3001"
```

...but they still can't talk to each other. From what I can tell, this is because `API_URL=http://localhost:3000` in [env.local](client/.env.local) gets baked in on build so setting it as a runtime env variable has no effect.

I just came across [this article](https://medium.com/@albertfrimpong/access-runtime-environment-variable-in-a-webpack-app-248448246f24) which may help?

I would try my hand at fixing this particular issue but I'm not familiar with NextJS so it'd probably take me a while 😅
